# 只允许 只允许你指定的 IP / IP 段访问服务
# 单个 IP：192.168.1.10
# CIDR 段：192.168.1.0/24
[http.middlewares.m-internal-ip-allow.ipAllowList]
sourceRange = [
    "127.0.0.1",          # 本机
    "192.168.1.0/24",     # 内网
    "10.0.0.0/8",         # 内网     
  ]
 # 不允许的IP直接返回404，假装不存在 通常是403
 rejectStatusCode = 404