[http.routers.whoami-api]

entryPoints = ["web"]

rule = "Host(`10.0.1.7`)&& PathPrefix(`/whoami`)"

# middlewares = ["strip-perfix"]  
# middlewares = ["compress","ip-rate-limit","strip-perfix","ip-allow"]  
middlewares = ["internal-ip-allow","ip-rate-limit","strip-perfix"]  

service = "whoami-api"
 
[http.routers.whoami-api.observability]
accessLogs = true


