[http.routers.my-api]

# 绑定入口点 多个入口点用数组
# 不写 = 绑定所有入口点
entryPoints = ["web"]

# HTTP 路由器（规则匹配） 
# 请求进来 → 代入 Rule → 结果为 true → 匹配成功 → 交给这个路由处理

# Host(demo.com) 匹配请求的域名
# Path(/api/user) 精确匹配路径,要一比一的相同
# PathPrefix(/api) 前缀匹配路径
# Method(GET) 匹配请求方法
# Headers(X-Auth, true) 匹配请求头
# ClientIP(192.168.1.0/24) 匹配客户端 IP. IP 白名单
# Query(id, 123) 匹配 URL 参数

# || （或 → 满足一个就行）
# rule = "Host(`api.example.com`) || Host(`app.example.com`)"

# () 括号（分组，改变优先级）
# rule = "Host(`example.com`) && (Path(`/a`) || Path(`/b`))"
 
#  开启 TLS Traefik 会根据你 router 里的 rule = Host(...) 域名，
#  自动去全局 [tls] 证书列表里匹配最匹配的证书

# 收到请求 https://api.example.com
# 看到 Host: api.example.com

# && （且 → 必须同时满足）
# 必须域名 + 路径同时匹配才生效
rule = "Host(`172.24.171.242`)&&Path(`/whoami`)"


# 使用中间件
# ip-rate-limit 限流
# strip-pefix   转发去前缀
# ip-allow IP   白名单
# scope-iot-basic-auth 加 headers
# forward-oidc-auth 转发 oidc 认证
middlewares = ["ip-rate-limit","strip-pefix","ip-allow","scope-iot-basic-auth","forward-oidc-auth"]  


# 绑定的后端服务
service = "api-backend"


# 扫描全局所有 [[tls.certificates]]
# 找到包含 api.example.com 域名的证书
# 自动使用它
[http.routers.my-api.tls] 

# 可观测性-开启访问日志
[http.routers.my-api.observability]
accessLogs = true


# loadBalancer 和 weighted，只能选一个

# loadBalancer: 把请求均匀转发到多个后端服务器
# 支持：轮询、最少连接、健康检查、超时、粘性会话
# 场景：Web 服务、API 服务、常规微服务
[http.services.api-backend.loadBalancer]


# 转发策略：

# wrr 轮询 顺序规则
# 按顺序轮流转发请求给后端
# 它记住上一次发给了谁，下一次直接取下一个
# 完全轮流，均匀分发
# 支持权重（默认所有节点权重相同）, 给后端设置权重，让性能好的机器多扛流量 权重越高，被选中次数越多！


# p2c 次随机选择
# 随机选 2 个后端 
# 选择其中 连接数更少 的一个
# 比轮询更均衡，比最少连接更快

# 优点
# 非常均衡
# 性能极高
# 抗雪崩、抗热点
# 适合高并发、长连接场景

# 高并发 API & gRPC & 长连接 &大规模微服务


# hrw 一致性哈希
# 根据 客户端 IP / 源地址 / 域名 / 请求参数 做哈希
# 同一个客户端 永远命中同一个后端 
# 节点上下线 只影响少量用户（一致性哈希）

# 优点
# 天然会话保持（不需要 Cookie）
# 有状态服务必备
# 节点扩缩容影响最小


# leasttime 最小响应时间
# 最少活跃连接
# 最快平均响应时间

# 优点：
# 最智能
# 自动避开慢节点
# 自动降低延迟
# 适合后端性能不一致的场景
strategy = "wrr"

# 是否转发原始 Host 头
# 用户访问 Host: api.com
# Traefik 转发给后端 Host: api.com
passHostHeader = true

# 使用对应的传输配置
# serversTransport = "upload-timeout-transport"

# 会话粘性（会话保持）
# 让同一个客户端的请求，始终落到同一台后端 （基于 Cookie 实现）
[http.services.api-backend.loadBalancer.sticky.cookie]
# 自定义Cookie名
name = "my_sticky_cookie"
# HTTPS Only
secure = true              
httpOnly = true


# 健康检查（可选）
# Traefik 定期向后端发送请求，自动剔除不健康节点
[http.services.api-backend.loadBalancer.healthCheck]
mode="http"
path = "/api/health"     # 检查路径
interval = "10s"         # 检查间隔
timeout = "5s"           # 超时时间
status = "200"           # 健康状态码


# 后端服务器列表
[[http.services.api-backend.loadBalancer.servers]]
# 必须写：协议 + IP/域名 + 端口
url = "http://127.0.0.1:801"

# WRR 加权轮询的权重 不写 =权重 1
# 数字越大，这台服务器分到的请求越多
weight=3

# 转发时是否保留原始请求路径
# https://info-gw.singworld.cn/aamiot-v5/api/ProductBasic/InfoTypePage?isAll=true
# false 例子
# backend  url = "http://127.0.0.1:8080/api"
# 客户端访问 http://traefik/user/profile
# Traefik 转发的最终地址：http://127.0.0.1:8080/api/user/profile
# 后端 URL 里的 /api + 客户端路径 /user/profile 拼接了

# true 例子
# backend  url = "http://127.0.0.1:8080/api"
# 客户端访问 http://traefik/user/profile
# 实际转发：http://127.0.0.1:8080/user/profile
preservePath = false


[[http.services.api-backend.loadBalancer.servers]]
url = "http://127.0.0.2:802"
weight=1
preservePath = true