# docker-compose -f ./docker-compose-2.yml up -d
services:
  whoami2:
    container_name: whoami2
    hostname: whoami2
    image: crpi-p35inr9lrgirg3t0.cn-hangzhou.personal.cr.aliyuncs.com/yaobo-box/whoami:1.0.4
    ports:
      - "802:3000"
    restart: always