version: '3.7'
services:
  traefik:
    container_name: traefik
    image: crpi-p35inr9lrgirg3t0.cn-hangzhou.personal.cr.aliyuncs.com/yaobo-box/traefik:v3.6.14
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/etc/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/providers:/providers
      - $PWD/log:/var/log
